
seed: 0
optimizer: rea_svr
search_space: darts
dataset: cifar10
out_dir: run

search:
  budgets: 50000000
  seed: 0
  checkpoint_freq: 1000
  epochs: 500
  fidelity: 200

  predictor_type: bananas
  num_init: 10  
  k: 10

  # BANANAS
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 5
  max_mutations: 1
  num_candidates: 200
  
  # data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
